### ISSUE TITLE
In Windows, all arguments are not recognized

### ISSUE THREAD

**Issue by NotWoods** [FormidableLabs/pull-report#13]
Running pull-report with any command, including `--help`, throws the following error:
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at Object.<anonymous> (C:\Users\tiger\AppData\Roaming\npm\node_modules\pull-report\pull-report.js:20:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
```

The command works fine in the Bash subsystem on Windows 10. Node.js version is 6.7.0

**Comment by ryan-roemer** [comment]
Confirmed:

```
X:\scm>pull-report -h
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at Object.<anonymous> (C:\Users\IEUser\AppData\Roaming\nvm\v4.5.0\node_modul
es\pull-report\pull-report.js:20:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

For Node 4.5.0 too.
